server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bodywhy
    username: bodywhy
    password: bodywhy

  ai:
    openai:
      base-url: https://api.groq.com/openai
      api-key: ${GROQ_API_KEY:}
      chat:
        options:
          model: llama-3.3-70b-versatile

logging:
  level:
    com.bodywhy: DEBUG